version: "3"
services:
  go-templater:
    image: go-templater
    environment: 
      MQ_HOST: kafka
      MQ_PORT: 9092
    volumes: 
      - ../.vscode:/template

  zookeeper:
    image: wurstmeister/zookeeper
    hostname: zookeeper
    ports:
      - 2181:2181

  kafka:
    image: wurstmeister/kafka
    ports:
      - 9092:9092
      - 9093:9093
    environment:
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_AUTO_CREATE_TOPICS_ENABLE=true
      - KAFKA_ADVERTISED_HOST_NAME=kafka
      - KAFKA_ADVERTISED_LISTENERS=INSIDE://kafka:9092,OUTSIDE://localhost:9093
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      - KAFKA_LISTENERS=INSIDE://kafka:9092,OUTSIDE://0.0.0.0:9093
      - KAFKA_INTER_BROKER_LISTENER_NAME=INSIDE
      - KAFKA_REPLICA_FETCH_MAX_BYTES=50000000
      - KAFKA_PRODUCER_MAX_REQUEST_SIZE=50000000
      - KAFKA_CONSUMER_MAX_PARTITION_FETCH_BYTES=50000000
      - CONNECT_PRODUCER_MAX_REQUEST_SIZE=50000000
      - CONNECT_CONSUMER_MAX_PARTITION_FETCH_BYTES=50000000
      - KAFKA_MESSAGE_MAX_BYTES=50000000
      - KAFKA_CREATE_TOPICS="request:1:1,response:1:1"
    volumes:
      - kafka_data:/kafka
    depends_on:
      - zookeeper

volumes:
  kafka_data: